// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Banner: typeof import('./src/components/Banner.vue')['default']
    Comment: typeof import('./src/components/Comment/index.vue')['default']
    CommentForm: typeof import('./src/components/Comment/CommentForm.vue')['default']
    CommentItem: typeof import('./src/components/Comment/CommentItem.vue')['default']
    CommentList: typeof import('./src/components/Comment/CommentList.vue')['default']
    CommentSkeleton: typeof import('./src/components/Comment/CommentSkeleton.vue')['default']
    CommentStatus: typeof import('./src/components/Comment/CommentStatus.vue')['default']
    Footer: typeof import('./src/components/Footer.vue')['default']
    Github: typeof import('./src/components/Github.vue')['default']
    Header: typeof import('./src/components/Header/index.vue')['default']
    ListCategories: typeof import('./src/components/ListCategories.vue')['default']
    ListPosts: typeof import('./src/components/ListPosts.vue')['default']
    ListProjects: typeof import('./src/components/ListProjects.vue')['default']
    Logo: typeof import('./src/components/Header/Logo.vue')['default']
    Markdown: typeof import('./src/components/Markdown.vue')['default']
    NavBar: typeof import('./src/components/Header/NavBar.vue')['default']
    Post: typeof import('./src/components/Post.vue')['default']
    PostMeta: typeof import('./src/components/PostMeta.vue')['default']
    Redirect: typeof import('./src/components/Redirect.vue')['default']
    RightBtns: typeof import('./src/components/Header/RightBtns.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Space: typeof import('./src/components/Space.vue')['default']
  }
}
