// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Github: typeof import('./src/components/Github.vue')['default']
    Header: typeof import('./src/components/Header.vue')['default']
    Mardown: typeof import('./src/components/Mardown.vue')['default']
    Markdown: typeof import('./src/components/Markdown.vue')['default']
    Post: typeof import('./src/components/Post.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
