// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Article: typeof import('./src/components/Article.vue')['default']
    Author: typeof import('./src/components/Header/Author.vue')['default']
    Github: typeof import('./src/components/Github.vue')['default']
    Header: typeof import('./src/components/Header/index.vue')['default']
    Markdown: typeof import('./src/components/Markdown.vue')['default']
    NavBar: typeof import('./src/components/Header/NavBar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TopMeta: typeof import('./src/components/Header/TopMeta.vue')['default']
  }
}
